name: NodeJS deployment

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.19.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: "build"
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        yarn deploy -u "github-actions-bot <support+actions@github.com>"
      if: ${{ github.ref == 'refs/heads/master' }} # only deploy master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Deploy to GitHub Pages
    #   uses: JamesIves/github-pages-deploy-action@v6
    #   with:
    #       branch: gh-pages
    #       folder: dist/malaka-senanayake-portfolio/browser   # <-- include /browser
    #       clean: true
